#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#define DEBUG			0
#define UNICAST_CHANNEL 	137
#define SAMPLING_INTERVAL	5*CLOCK_SECOND
#define SINK_ADDRESS		0x0017
#define FIREFLY_RATED_CURRENT	1
#define FIREFLY_RATED_VOLTAGE	3.3 //v
#define FIREFLY_CPU_CURRENT	0.6 //mA
#define FIREFLY_LPM_CURRENT	0.0013 //mA
#define FIREFLY_TX_CURRENT	24.0 //mA
#define FIREFLY_RX_CURRENT	20.0 //mA
#define FIREFLY_TX_CURRENT_IDLE 0.25*FIREFLY_TX_CURRENT
#define FIREFLY_RX_CURRENT_IDLE 0.25*FIREFLY_RX_CURRENT

#endif
